import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import {
  END_MARKER,
  SKIP_MARKER,
  START_MARKER,
  findBlock,
  hasSkipMarker,
  outsideLength,
  upsertBlock,
} from '../../src/body/markers'

/**
 * This module is the one that can destroy a human's writing, so the matrix is
 * deliberately exhaustive and the central assertion is repeated in every
 * replacement case: the text before the start marker and after the end marker
 * comes back byte-for-byte. That is asserted directly against the substrings,
 * never through a snapshot — a snapshot would happily record the damage.
 */

/** A realistic block, shaped like the one the assembler emits. */
const BLOCK = [
  START_MARKER,
  'Closes #142',
  '',
  '## Commits',
  '',
  '- 2026-07-28 09:14 — [`a1b2c3d`](https://example.invalid/commit/a1b2c3d) — @alice — feat: rotate tokens',
  '',
  '<sub>Generated by pr-decorator · head 9c8d7e6 · 1 commit · times in Europe/Berlin</sub>',
  END_MARKER,
].join('\n')

/** A second render of the same block, one commit later. */
const NEXT_BLOCK = [
  START_MARKER,
  'Closes #142',
  '',
  '## Commits',
  '',
  '- 2026-07-28 09:14 — [`a1b2c3d`](https://example.invalid/commit/a1b2c3d) — @alice — feat: rotate tokens',
  '- 2026-07-28 11:02 — [`e4f5a6b`](https://example.invalid/commit/e4f5a6b) — @bob — test: cover expiry',
  '',
  '<sub>Generated by pr-decorator · head e4f5a6b · 2 commits · times in Europe/Berlin</sub>',
  END_MARKER,
].join('\n')

const AUTHOR_PREFIX = '## Why\n\nThe refresh token never rotated.\n\n'
const AUTHOR_SUFFIX = '\n\n## Notes\n\nReview the migration first.\n'

/** An author body with the block sitting in the MIDDLE of their own prose. */
const BODY_WITH_MIDDLE_BLOCK = `${AUTHOR_PREFIX}${BLOCK}${AUTHOR_SUFFIX}`

/** The author's text on either side of the located block. */
function outsideParts(text: string): { before: string; after: string } {
  const range = findBlock(text)
  if (range === null) {
    throw new Error('expected the fixture to contain a complete block')
  }
  return { before: text.slice(0, range.start), after: text.slice(range.end) }
}

/** Compares two strings character by character, so a diff names the index. */
function expectCharForChar(actual: string, expected: string): void {
  expect(actual.length).toBe(expected.length)
  for (let index = 0; index < expected.length; index += 1) {
    expect([index, actual[index]]).toEqual([index, expected[index]])
  }
}

describe('hasSkipMarker', () => {
  it('is true for a body that carries the opt-out marker', () => {
    expect(hasSkipMarker(`${AUTHOR_PREFIX}${SKIP_MARKER}\n`)).toBe(true)
  })

  it('is true when the marker sits alongside an existing managed block', () => {
    // The realistic opt-out: the author let one run happen, then said no more.
    expect(hasSkipMarker(`${SKIP_MARKER}\n\n${BODY_WITH_MIDDLE_BLOCK}`)).toBe(true)
  })

  it('is true mid-sentence, because opting out is a deliberate act', () => {
    expect(hasSkipMarker(`Please stop: ${SKIP_MARKER} thanks.`)).toBe(true)
  })

  it('is false for a body without it, including the block itself', () => {
    expect(hasSkipMarker(BODY_WITH_MIDDLE_BLOCK)).toBe(false)
  })

  it('is false for null and for an empty body', () => {
    expect(hasSkipMarker(null)).toBe(false)
    expect(hasSkipMarker('')).toBe(false)
  })

  it('is false for the stripped remnant of a marker-shaped commit subject', () => {
    // The commit renderer removes literal marker text from a subject outright,
    // so what survives into the block can never re-introduce the opt-out.
    const stripped = BLOCK.replace(
      'feat: rotate tokens',
      'feat: stop decorating  and move on',
    )
    expect(stripped).toContain('stop decorating  and move on')
    expect(hasSkipMarker(stripped)).toBe(false)
  })

  it('is false for the escaped form the author renderer produces', () => {
    // A git author name spelled like the marker comes through with both angle
    // brackets escaped, which is visible text and not a marker.
    expect(hasSkipMarker('- @alice \\<!-- pr-decorator:skip --\\> — feat: x')).toBe(false)
  })
})

describe('findBlock', () => {
  it('returns null for null, empty and marker-free bodies', () => {
    expect(findBlock(null)).toBeNull()
    expect(findBlock('')).toBeNull()
    expect(findBlock(AUTHOR_PREFIX)).toBeNull()
  })

  it('spans exactly the block, wherever it sits in the body', () => {
    for (const body of [BLOCK, `${BLOCK}${AUTHOR_SUFFIX}`, BODY_WITH_MIDDLE_BLOCK]) {
      const range = findBlock(body)
      expect(range).not.toBeNull()
      expect(body.slice(range!.start, range!.end)).toBe(BLOCK)
    }
  })

  it('excludes the newline that terminates the end-marker line', () => {
    const range = findBlock(BODY_WITH_MIDDLE_BLOCK)
    // That newline is the author's: it separates their prose from the block.
    expect(BODY_WITH_MIDDLE_BLOCK.slice(range!.end)).toBe(AUTHOR_SUFFIX)
  })

  it('returns null for a start marker with no end after it', () => {
    expect(findBlock(`${AUTHOR_PREFIX}${START_MARKER}\nCloses #142\n`)).toBeNull()
  })

  it('returns null for an end marker with no start before it', () => {
    expect(findBlock(`${AUTHOR_PREFIX}${END_MARKER}\n`)).toBeNull()
  })

  it('ignores an end marker that precedes the start', () => {
    const body = `${END_MARKER}\n\n${BLOCK}\n`
    const range = findBlock(body)
    expect(body.slice(range!.start, range!.end)).toBe(BLOCK)
  })

  it('matches a marker only as a whole line, never inside prose', () => {
    const quoted = `We write ${START_MARKER} and ${END_MARKER} into the body.\n`
    expect(findBlock(quoted)).toBeNull()
  })

  it('does not match an indented marker line', () => {
    // An indented line is a different construct in markdown; matching it would
    // let a quotation inside a list item move the block.
    expect(findBlock(`    ${START_MARKER}\n    ${END_MARKER}\n`)).toBeNull()
  })

  it('finds its own block in a body that came back with CRLF line endings', () => {
    // The web form rewrites line endings; failing here would append a second
    // block on every run.
    const body = `${AUTHOR_PREFIX}${BLOCK}`.replace(/\n/g, '\r\n')
    const range = findBlock(body)
    expect(range).not.toBeNull()
    expect(body.slice(range!.start, range!.end)).toBe(BLOCK.replace(/\n/g, '\r\n'))
  })

  it('tolerates trailing whitespace on a marker line', () => {
    const body = `${START_MARKER}  \nblock\n${END_MARKER}\t\n`
    const range = findBlock(body)
    expect(body.slice(range!.start, range!.end)).toBe(`${START_MARKER}  \nblock\n${END_MARKER}\t`)
  })

  it('answers identically on repeated calls', () => {
    // The patterns are module-level; a /g flag would make the second call lie.
    expect(findBlock(BODY_WITH_MIDDLE_BLOCK)).toEqual(findBlock(BODY_WITH_MIDDLE_BLOCK))
  })
})

describe('upsertBlock on an empty body', () => {
  it('turns null into exactly the block, with no stray whitespace', () => {
    const result = upsertBlock(null, BLOCK, 'top')
    expect(result).toEqual({ body: BLOCK, action: 'inserted' })
    expect(result.body).toBe(result.body.trim())
  })

  it('turns an empty body into exactly the block, whatever the position', () => {
    const result = upsertBlock('', BLOCK, 'bottom')
    expect(result).toEqual({ body: BLOCK, action: 'inserted' })
    expect(result.body).toBe(result.body.trim())
  })
})

describe('upsertBlock inserting a first block', () => {
  const author = 'Some prose the author wrote.'

  it('puts the block first at the top, separated by one blank line', () => {
    const result = upsertBlock(author, BLOCK, 'top')
    expect(result.action).toBe('inserted')
    expect(result.body).toBe(`${BLOCK}\n\n${author}`)
  })

  it('puts the block last at the bottom, separated by one blank line', () => {
    const result = upsertBlock(author, BLOCK, 'bottom')
    expect(result.action).toBe('inserted')
    expect(result.body).toBe(`${author}\n\n${BLOCK}`)
  })

  it('keeps every byte of the author text on insertion', () => {
    for (const position of ['top', 'bottom'] as const) {
      const body = upsertBlock(AUTHOR_PREFIX, BLOCK, position).body
      const { before, after } = outsideParts(body)
      expect(`${before}${after}`.includes(AUTHOR_PREFIX)).toBe(true)
    }
  })

  it('tops up the separator instead of trimming the author text', () => {
    // Trimming would be a deletion of bytes the author wrote. The separator only
    // ever adds, so a body already ending in a blank line grows by nothing.
    expect(upsertBlock('text\n\n', BLOCK, 'bottom').body).toBe(`text\n\n${BLOCK}`)
    expect(upsertBlock('text\n', BLOCK, 'bottom').body).toBe(`text\n\n${BLOCK}`)
    expect(upsertBlock('\n\ntext', BLOCK, 'top').body).toBe(`${BLOCK}\n\ntext`)
    expect(upsertBlock('\ntext', BLOCK, 'top').body).toBe(`${BLOCK}\n\ntext`)
  })

  it('emits the block verbatim, without escaping or reformatting it', () => {
    const raw = `${START_MARKER}\n  indented\ttab \n${END_MARKER}`
    expect(upsertBlock(null, raw, 'top').body).toBe(raw)
  })
})

describe('upsertBlock replacing an existing block', () => {
  it.each(['top', 'bottom'] as const)(
    'replaces a middle block in place with position %s, without moving it',
    (position) => {
      const result = upsertBlock(BODY_WITH_MIDDLE_BLOCK, NEXT_BLOCK, position)

      expect(result.action).toBe('replaced')
      expect(result.body).toBe(`${AUTHOR_PREFIX}${NEXT_BLOCK}${AUTHOR_SUFFIX}`)
      // The block did not travel to either end of the body.
      expect(result.body.startsWith(AUTHOR_PREFIX)).toBe(true)
      expect(result.body.endsWith(AUTHOR_SUFFIX)).toBe(true)
    },
  )

  it('leaves the text outside the markers byte-identical, character for character', () => {
    const before = outsideParts(BODY_WITH_MIDDLE_BLOCK)
    const after = outsideParts(upsertBlock(BODY_WITH_MIDDLE_BLOCK, NEXT_BLOCK, 'top').body)

    expectCharForChar(after.before, before.before)
    expectCharForChar(after.after, before.after)
  })

  it('preserves the author text around a block at the top and at the bottom', () => {
    for (const body of [`${BLOCK}${AUTHOR_SUFFIX}`, `${AUTHOR_PREFIX}${BLOCK}`]) {
      const source = outsideParts(body)
      const result = outsideParts(upsertBlock(body, NEXT_BLOCK, 'top').body)
      expectCharForChar(result.before, source.before)
      expectCharForChar(result.after, source.after)
    }
  })

  it('replaces the block a first write put at the bottom, position notwithstanding', () => {
    const inserted = upsertBlock(AUTHOR_PREFIX, BLOCK, 'bottom').body
    const replaced = upsertBlock(inserted, NEXT_BLOCK, 'top')

    expect(replaced.action).toBe('replaced')
    expect(replaced.body).toBe(inserted.replace(BLOCK, NEXT_BLOCK))
    expect(replaced.body.startsWith(AUTHOR_PREFIX)).toBe(true)
  })

  it('does not touch a skip marker the author added outside the block', () => {
    const body = `${SKIP_MARKER}\n\n${BODY_WITH_MIDDLE_BLOCK}`
    expect(upsertBlock(body, NEXT_BLOCK, 'top').body).toContain(SKIP_MARKER)
  })
})

describe('upsertBlock is idempotent', () => {
  it('returns a byte-identical body when the block is already exact', () => {
    const result = upsertBlock(BODY_WITH_MIDDLE_BLOCK, BLOCK, 'top')

    expect(result.action).toBe('replaced')
    // `===`, not `toEqual`: the entrypoint skips the write on this comparison.
    expect(result.body === BODY_WITH_MIDDLE_BLOCK).toBe(true)
  })

  it('reaches a fixed point after the first write, at either position', () => {
    for (const position of ['top', 'bottom'] as const) {
      const first = upsertBlock(AUTHOR_PREFIX, BLOCK, position).body
      const second = upsertBlock(first, BLOCK, position)
      expect(second.action).toBe('replaced')
      expect(second.body === first).toBe(true)
    }
  })
})

describe('upsertBlock refuses an unclosed block', () => {
  const truncated = `${AUTHOR_PREFIX}${START_MARKER}\nCloses #142\n\n## Commits\n`

  it('returns the input body unchanged and reports the unclosed action', () => {
    const result = upsertBlock(truncated, NEXT_BLOCK, 'top')

    expect(result.action).toBe('unclosed')
    // Identity, not equality: no copy, no re-encoding, no edit whatsoever.
    expect(result.body === truncated).toBe(true)
  })

  it('refuses at both positions rather than inserting a second start marker', () => {
    for (const position of ['top', 'bottom'] as const) {
      const result = upsertBlock(truncated, NEXT_BLOCK, position)
      expect(result.body).toBe(truncated)
      expect(result.body).not.toContain(NEXT_BLOCK)
    }
  })

  it('still inserts when the body only carries a stray end marker', () => {
    // An end with no start is prose, not a half-written block.
    const body = `${AUTHOR_PREFIX}${END_MARKER}\n`
    const result = upsertBlock(body, BLOCK, 'top')
    expect(result.action).toBe('inserted')
    expect(result.body).toBe(`${BLOCK}\n\n${body}`)
  })
})

describe('markers inside a fenced code block', () => {
  const FENCE = '```'
  const documented = [
    'The block looks like this:',
    '',
    `${FENCE}markdown`,
    START_MARKER,
    'Closes #1',
    END_MARKER,
    FENCE,
    '',
    'Nothing else to say.',
  ].join('\n')

  it('treats a fenced marker as a real one, which is the documented limitation', () => {
    // A literal line scan cannot tell the two apart. The behaviour is pinned so
    // that a future markdown-aware change is a deliberate one.
    const range = findBlock(documented)
    expect(range).not.toBeNull()
    expect(documented.slice(range!.start, range!.end)).toBe(
      `${START_MARKER}\nCloses #1\n${END_MARKER}`,
    )
  })

  it('is non-destructive: the fence and all surrounding text survive', () => {
    const source = outsideParts(documented)
    const result = upsertBlock(documented, NEXT_BLOCK, 'top')
    const kept = outsideParts(result.body)

    expect(result.action).toBe('replaced')
    expectCharForChar(kept.before, source.before)
    expectCharForChar(kept.after, source.after)
    expect(result.body).toContain(`${FENCE}markdown`)
    expect(result.body).toContain('Nothing else to say.')
  })

  it('is deterministic across repeated calls', () => {
    const once = upsertBlock(documented, NEXT_BLOCK, 'top')
    const twice = upsertBlock(documented, NEXT_BLOCK, 'top')
    expect(once).toEqual(twice)
  })
})

describe('outsideLength', () => {
  it('is zero for null and for an empty body', () => {
    expect(outsideLength(null)).toBe(0)
    expect(outsideLength('')).toBe(0)
  })

  it('is the whole length when there is no block', () => {
    expect(outsideLength(AUTHOR_PREFIX)).toBe(AUTHOR_PREFIX.length)
  })

  it('counts only the author text when a block is present', () => {
    expect(outsideLength(BODY_WITH_MIDDLE_BLOCK)).toBe(
      AUTHOR_PREFIX.length + AUTHOR_SUFFIX.length,
    )
  })

  it('leaves the whole body counted when the block is unclosed', () => {
    // Conservative in the right direction; that body is never written anyway.
    const truncated = `${AUTHOR_PREFIX}${START_MARKER}\n`
    expect(outsideLength(truncated)).toBe(truncated.length)
  })

  it('is the budget complement: block length plus outside length is the body', () => {
    const range = findBlock(BODY_WITH_MIDDLE_BLOCK)!
    expect(outsideLength(BODY_WITH_MIDDLE_BLOCK) + (range.end - range.start)).toBe(
      BODY_WITH_MIDDLE_BLOCK.length,
    )
  })

  it('measures UTF-16 code units, the unit the budget arithmetic uses', () => {
    // An astral character counts as two, which over-counts against the real
    // limit and therefore errs on the safe side.
    expect(outsideLength('🚀')).toBe(2)
  })
})

describe('module boundaries', () => {
  const source = readFileSync(
    fileURLToPath(new URL('../../src/body/markers.ts', import.meta.url)),
    'utf8',
  )

  it('reads the source it is asserting over', () => {
    // Guards the assertions below against an empty read passing vacuously.
    expect(source).toContain('export function upsertBlock')
  })

  it.each(['@actions', 'octokit', 'Octokit', 'fetch(', 'node:'])(
    'never mentions %s — the module is pure and does no I/O',
    (forbidden) => {
      // A byte-literal check, comments included: prose naming a forbidden
      // dependency fails the same grep in CI as a real import would.
      expect(source).not.toContain(forbidden)
    },
  )

  it('imports nothing but the shared Position type', () => {
    const imports = source.match(/^[ \t]*import\b.*$/gm) ?? []
    expect(imports).toEqual(["import type { Position } from '../types'"])
  })
})
