/**
 * The footer: one line saying what wrote the block, from which head commit, over
 * how many commits, and in which timezone.
 *
 * It exists to make the block self-explaining. A reader who has never heard of
 * this action finds the name of the thing that edited their pull request body, and
 * a reader puzzled by a timestamp finds the zone it was rendered in without having
 * to open the workflow file. Both are questions the block would otherwise raise
 * and not answer.
 *
 * Wrapped in `<sub>`, which GitHub-Flavored Markdown renders as smaller text, so
 * the line reads as provenance rather than as content. It is the only HTML this
 * action emits, and it emits it because markdown has no smaller-text construct.
 *
 * The commit count is the pull request's TOTAL, not the number of bullets above
 * it. Those two differ whenever the API ceiling or the character budget dropped
 * something, and the total is the honest answer to "how big is this pull request" —
 * the list already carries its own notes about what it is not showing.
 *
 * Every field here is generated by this action, never by a commit author, so
 * nothing on this line needs neutralizing. The one value that comes from outside
 * is the timezone, which was validated as an IANA name before it reached here.
 */

/**
 * Field separator: space, MIDDLE DOT (U+00B7), space. Not a bullet (U+2022) and
 * not the EM DASH the commit bullets use — the footer is a different register and
 * reads better with a lighter separator. A test pins the code point, since a
 * middle dot and a bullet are hard to tell apart in a diff.
 */
const FIELD_SEPARATOR = ' · '

/** What the footer needs, and nothing more. */
export interface FooterOptions {
  /**
   * The head commit's abbreviated SHA, already shortened by the caller with the
   * same rule the bullets use. Abbreviating here would be a second answer to a
   * question the commit renderer already answers.
   */
  headShortSha: string
  /**
   * The pull request's TOTAL commit count, straight from the pull request object.
   * May exceed the number of bullets rendered above the footer.
   */
  commitCount: number
  /** IANA zone name the timestamps above were rendered in, emitted verbatim. */
  timeZone: string
}

/** `commit` or `commits`, because `1 commits` reads like a bug. */
function commitNoun(count: number): string {
  return count === 1 ? 'commit' : 'commits'
}

/**
 * Renders the footer line.
 *
 * @param options - The head SHA, the total commit count and the timezone name.
 * @returns One line, no trailing newline, e.g.
 *   `<sub>Generated by pr-decorator · head 9c8d7e6 · 3 commits · times in Europe/Berlin</sub>`.
 *   How it is spaced against the rest of the block is the assembler's decision.
 */
export function renderFooter(options: FooterOptions): string {
  const fields = [
    'Generated by pr-decorator',
    `head ${options.headShortSha}`,
    `${options.commitCount} ${commitNoun(options.commitCount)}`,
    `times in ${options.timeZone}`,
  ]
  return `<sub>${fields.join(FIELD_SEPARATOR)}</sub>`
}
