import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { renderFooter, type FooterOptions } from '../../src/render/footer'

/**
 * The footer is one line and its whole contract is what that line says, so the
 * tests below are mostly exact-string assertions. The two that are not cover the
 * things a string comparison cannot show: that the separator really is a middle
 * dot rather than something that merely looks like one in a diff, and that the
 * count on the line is the pull request's total rather than the number of bullets
 * rendered above it.
 */

/** The reference options from the issue's normative block. */
const REFERENCE: FooterOptions = {
  headShortSha: '9c8d7e6',
  commitCount: 3,
  timeZone: 'Europe/Berlin',
}

/** MIDDLE DOT (U+00B7), the character the separator must be built from. */
const MIDDLE_DOT = '·'

describe('the reference footer', () => {
  it('renders exactly the line the normative block carries', () => {
    expect(renderFooter(REFERENCE)).toBe(
      '<sub>Generated by pr-decorator · head 9c8d7e6 · 3 commits · times in Europe/Berlin</sub>',
    )
  })

  it('is a single line with no trailing newline, so the assembler owns the spacing', () => {
    const footer = renderFooter(REFERENCE)

    expect(footer.split('\n')).toHaveLength(1)
    expect(footer).toBe(footer.trim())
  })

  it('wraps the whole line in <sub> and nothing else', () => {
    const footer = renderFooter(REFERENCE)

    expect(footer.startsWith('<sub>')).toBe(true)
    expect(footer.endsWith('</sub>')).toBe(true)
    expect(footer.match(/<sub>/g)).toHaveLength(1)
  })
})

describe('the separator', () => {
  it('is a middle dot by code point, not a bullet that resembles one', () => {
    const separators = renderFooter(REFERENCE).match(new RegExp(MIDDLE_DOT, 'g'))

    expect(separators).toHaveLength(3)
    expect(renderFooter(REFERENCE)).toContain(` ${MIDDLE_DOT} `)
    // U+2022 BULLET and U+2027 HYPHENATION POINT both read as a middle dot in a
    // proportional font, and either would silently replace it.
    expect(renderFooter(REFERENCE)).not.toMatch(/[•‧]/)
  })

  it('separates exactly four fields', () => {
    const fields = renderFooter(REFERENCE)
      .replace(/^<sub>|<\/sub>$/g, '')
      .split(` ${MIDDLE_DOT} `)

    expect(fields).toEqual([
      'Generated by pr-decorator',
      'head 9c8d7e6',
      '3 commits',
      'times in Europe/Berlin',
    ])
  })
})

describe('the commit count', () => {
  it('reads `1 commit` in the singular', () => {
    expect(renderFooter({ ...REFERENCE, commitCount: 1 })).toContain(`${MIDDLE_DOT} 1 commit ${MIDDLE_DOT}`)
  })

  it.each([0, 2, 3, 250])('reads `%i commits` in the plural', (count) => {
    expect(renderFooter({ ...REFERENCE, commitCount: count })).toContain(
      `${MIDDLE_DOT} ${count} commits ${MIDDLE_DOT}`,
    )
  })

  it('is the pull request total, which may exceed the number of bullets rendered', () => {
    // The normative block shows two bullets under a pull request of three commits.
    // The footer takes its count from the pull request object and knows nothing
    // about how many bullets survived the ceiling or the character budget.
    expect(renderFooter({ ...REFERENCE, commitCount: 3 })).toContain('3 commits')
  })
})

describe('the remaining fields', () => {
  it('emits the zone name verbatim, whatever shape it has', () => {
    for (const timeZone of ['UTC', 'Europe/Berlin', 'America/Argentina/Buenos_Aires', 'Etc/GMT+5']) {
      expect(renderFooter({ ...REFERENCE, timeZone })).toContain(`times in ${timeZone}</sub>`)
    }
  })

  it('emits the short SHA it was handed, without re-abbreviating it', () => {
    // Shortening is the caller's job, applied with the same rule the bullets use.
    // A second abbreviation here would be a second answer to one question.
    const full = 'a1b2c3d4e5f60718293a4b5c6d7e8f9012345678'

    expect(renderFooter({ ...REFERENCE, headShortSha: full })).toContain(`head ${full} `)
  })
})

describe('module boundaries', () => {
  const source = readFileSync(
    fileURLToPath(new URL('../../src/render/footer.ts', import.meta.url)),
    'utf8',
  )

  it('reads the source it is asserting over', () => {
    expect(source).toContain('export function renderFooter')
  })

  it.each(['@actions', 'src/github', "from '../github", 'octokit'])(
    'never mentions %s anywhere, comments included, as the pure render layer',
    (forbidden) => {
      expect(source).not.toContain(forbidden)
    },
  )

  it('imports nothing at all', () => {
    expect(source).not.toMatch(/^import /m)
  })
})
