import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { END_MARKER, START_MARKER, outsideLength, upsertBlock } from '../../src/body/markers'
import {
  renderCommitBullet,
  renderCommits,
  type CommitBulletOptions,
  type CommitSectionOptions,
} from '../../src/render/commits'
import { truncateCommits, type CommitMeasure } from '../../src/render/truncate'
import type { RenderableCommit } from '../../src/types'
import { buildCommit, buildCommits, nonMonotonicCommits } from '../fixtures/commits'

/**
 * Two kinds of test, and the split is deliberate.
 *
 * The selection arithmetic is proven against a STUB measure returning fixed
 * widths, so an assertion about "a budget that fits exactly three bullets" says
 * what it means and does not move the day someone changes the em dash.
 *
 * The property that actually matters — the assembled body never exceeds 65,536 —
 * is proven at the worst case the action can reach: 250 commits, the API ceiling,
 * with maximal realistic subjects, against an author body that already fills most
 * of the limit. The block around the commits section is built by a test-local
 * helper below rather than by the real assembler, which does not exist yet at this
 * point in the landing order; the same property is re-asserted against the real
 * assembler by #12's boundary golden and by #14's integration test. Triplicating
 * it is on purpose. An over-limit body is not a cosmetic failure — it is the one
 * failure that orphans a pull request body permanently.
 */

/** GitHub's hard cap on a pull request body, in UTF-16 code units (D10). */
const BODY_LIMIT = 65_536

/** The API ceiling the client enforces, and therefore the worst case here. */
const API_CEILING = 250

const RENDER_OPTIONS: CommitBulletOptions = {
  timeZone: 'Europe/Berlin',
  commitUrlBase: 'https://github.com/pgatzka/pr-decorator/commit',
}

function sectionOptions(counts: Partial<CommitSectionOptions>): CommitSectionOptions {
  return { ...RENDER_OPTIONS, totalCount: 1, returnedCount: 1, ...counts }
}

/** What #14 injects: the real bullet renderer, bound to the render options. */
const measureBullet: CommitMeasure = (commit) =>
  renderCommitBullet(commit, RENDER_OPTIONS).length

// --- the test-local block helper ------------------------------------------
//
// Markers, closing reference and footer concatenated by hand, in #12's layout.
// The marker literals are imported rather than retyped: a typo in a retyped
// marker is exactly the bug this whole file exists to prevent.

const CLOSING_LINE = 'Closes #142'

const FOOTER_LINE =
  '<sub>Generated by pr-decorator · head 9c8d7e6 · 250 commits · times in Europe/Berlin</sub>'

/** The block: start marker, `Closes`, blank, section, blank, footer, end marker. */
function buildBlock(section: string): string {
  return [START_MARKER, CLOSING_LINE, '', section, '', FOOTER_LINE, END_MARKER].join('\n')
}

/**
 * Everything in the block that is not the commits section. Derived by assembling
 * around an empty section rather than counted by hand, so it cannot drift from
 * the helper above.
 */
const BLOCK_OVERHEAD = buildBlock('').length

/**
 * What {@link upsertBlock} can add between the author's text and the block. Its
 * insertion is additive only — it tops trailing newlines up to one blank line and
 * never trims — so two characters is the maximum, reached by a body ending in no
 * newline at all. Every author body below ends that way.
 */
const SEPARATOR_COST = 2

/**
 * The section's own frame — heading plus its blank line — measured through the
 * renderer instead of hardcoded. One bullet costs its rendered length plus the
 * newline that puts it on its own line, and the remainder is the frame.
 */
const SECTION_OVERHEAD = (() => {
  const probe = buildCommit()
  const withOne = renderCommits([probe], sectionOptions({ totalCount: 1, returnedCount: 1 }))
  return withOne.length - measureBullet(probe) - 1
})()

/**
 * The overflow line at its worst case: the count reserved for is the full input
 * length, whose digit count is an upper bound for any achievable overflow.
 */
function overflowReserve(totalCount: number): number {
  const probe = buildCommit()
  const counts = { totalCount, returnedCount: totalCount }
  const plain = renderCommits([probe], sectionOptions(counts))
  const withNote = renderCommits([probe], sectionOptions({ ...counts, overflowCount: totalCount }))
  return withNote.length - plain.length
}

/** The budget #12 will compute, expressed here so the property can be asserted. */
function commitsBudget(authorBody: string, totalCount: number): number {
  return Math.max(
    0,
    BODY_LIMIT -
      outsideLength(authorBody) -
      SEPARATOR_COST -
      BLOCK_OVERHEAD -
      SECTION_OVERHEAD -
      overflowReserve(totalCount),
  )
}

/**
 * 250 commits at the worst size the renderer can be handed: a 72-character
 * subject, which is where the conventional git subject limit sits, and a login
 * near GitHub's own 39-character maximum.
 */
function worstCaseCommits(count: number): RenderableCommit[] {
  return buildCommits(
    Array.from({ length: count }, (_, index) => ({
      fullSha: index.toString(16).padStart(40, 'a'),
      authoredAt: new Date('2026-07-28T07:14:00.000Z'),
      mention: '@a-rather-long-but-legal-github-login-x',
      subject: `feat(auth): ${'rotate the refresh tokens and then some more '.repeat(2)}`.slice(
        0,
        72,
      ),
    })),
  )
}

/** An author body of `length` characters that ends WITHOUT a trailing newline. */
function authorBodyOf(length: number): string {
  const filler = 'Author prose that GitHub must not lose. '
  return filler.repeat(Math.ceil(length / filler.length) + 1).slice(0, length)
}

// --- the stub measure, for the selection arithmetic ------------------------

/** Every bullet the same width, so a budget can be stated in whole bullets. */
const STUB_WIDTH = 10

/** What one stubbed bullet costs in the section: its width plus its newline. */
const STUB_LINE = STUB_WIDTH + 1

const fixedWidth: CommitMeasure = () => STUB_WIDTH

/** Ten commits with distinct SHAs, so identity assertions cannot pass by accident. */
const TEN_COMMITS = buildCommits(
  Array.from({ length: 10 }, (_, index) => ({ fullSha: index.toString(16).padStart(40, 'b') })),
)

/**
 * A measure keyed by object identity. Doubles as proof that the commits reaching
 * `measure` are the caller's own objects: an unknown one throws rather than
 * quietly measuring zero.
 */
function measureFrom(widths: ReadonlyMap<RenderableCommit, number>): CommitMeasure {
  return (commit) => {
    const width = widths.get(commit)
    if (width === undefined) {
      throw new Error('measure was handed a commit that is not in the fixture')
    }
    return width
  }
}

/** Builds n commits and a width map over them, paired by position. */
function commitsWithWidths(widths: readonly number[]): {
  commits: RenderableCommit[]
  measure: CommitMeasure
} {
  const commits = buildCommits(
    widths.map((_, index) => ({ fullSha: index.toString(16).padStart(40, 'c') })),
  )
  const byCommit = new Map<RenderableCommit, number>()
  commits.forEach((commit, index) => byCommit.set(commit, widths[index] ?? 0))
  return { commits, measure: measureFrom(byCommit) }
}

describe('the assembled body never exceeds the limit', () => {
  const AUTHOR_BODY_SIZES = [0, 20_000, 40_000, 65_000]

  it.each(AUTHOR_BODY_SIZES)(
    '250 maximal commits under a %i-character author body stay inside 65,536',
    (authorSize) => {
      const authorBody = authorBodyOf(authorSize)
      const commits = worstCaseCommits(API_CEILING)
      const result = truncateCommits(
        commits,
        commitsBudget(authorBody, commits.length),
        measureBullet,
      )

      const section = renderCommits(
        result.commits,
        sectionOptions({
          totalCount: API_CEILING,
          returnedCount: API_CEILING,
          overflowCount: result.overflowCount,
        }),
      )
      const body = upsertBlock(authorBody, buildBlock(section), 'bottom').body

      expect(body.length).toBeLessThanOrEqual(BODY_LIMIT)
      expect(body).toContain(END_MARKER)
    },
  )

  it('spends nearly all of the room it was given, rather than playing it safe', () => {
    // A budget that always kept zero commits would pass the assertion above and
    // be useless. The leftover can only be the last bullet that did not fit plus
    // the few characters the worst-case overflow reservation over-counted.
    const authorBody = authorBodyOf(40_000)
    const commits = worstCaseCommits(API_CEILING)
    const result = truncateCommits(commits, commitsBudget(authorBody, commits.length), measureBullet)

    expect(result.commits.length).toBeGreaterThan(0)
    expect(result.overflowCount).toBeGreaterThan(0)

    const section = renderCommits(
      result.commits,
      sectionOptions({
        totalCount: API_CEILING,
        returnedCount: API_CEILING,
        overflowCount: result.overflowCount,
      }),
    )
    const body = upsertBlock(authorBody, buildBlock(section), 'bottom').body

    expect(body.length).toBeGreaterThan(BODY_LIMIT - 400)
    expect(body.length).toBeLessThanOrEqual(BODY_LIMIT)
  })

  it('still assembles a well-formed section when nothing at all fits', () => {
    const commits = worstCaseCommits(API_CEILING)
    const result = truncateCommits(commits, 0, measureBullet)

    expect(result).toEqual({ commits: [], overflowCount: API_CEILING })

    const section = renderCommits(
      result.commits,
      sectionOptions({
        totalCount: API_CEILING,
        returnedCount: API_CEILING,
        overflowCount: result.overflowCount,
      }),
    )
    expect(section).toBe('## Commits\n\nNo commits.\n\n… and 250 more commits')

    const body = upsertBlock(authorBodyOf(65_000), buildBlock(section), 'bottom').body
    expect(body.length).toBeLessThanOrEqual(BODY_LIMIT)
    expect(body).toContain(START_MARKER)
    expect(body).toContain(END_MARKER)
  })
})

describe('when everything fits', () => {
  it('reports no overflow and the section carries no overflow line', () => {
    const result = truncateCommits(nonMonotonicCommits, 10_000, measureBullet)

    expect(result.commits).toHaveLength(nonMonotonicCommits.length)
    expect(result.overflowCount).toBe(0)

    const section = renderCommits(
      result.commits,
      sectionOptions({
        totalCount: nonMonotonicCommits.length,
        returnedCount: nonMonotonicCommits.length,
        overflowCount: result.overflowCount,
      }),
    )
    expect(section).not.toContain('more commit')
    expect(section).not.toContain('…')
  })
})

describe('the selection arithmetic', () => {
  it.each([0, 1, 2, 5, 9, 10])('keeps exactly %i bullets when the budget fits that many', (k) => {
    const result = truncateCommits(TEN_COMMITS, k * STUB_LINE, fixedWidth)

    expect(result.commits).toHaveLength(k)
    expect(result.overflowCount).toBe(TEN_COMMITS.length - k)
  })

  it.each([1, 2, 5, 10])('drops the %ith bullet when one character is missing for it', (k) => {
    const result = truncateCommits(TEN_COMMITS, k * STUB_LINE - 1, fixedWidth)

    expect(result.commits).toHaveLength(k - 1)
  })

  it('does not take a partial bullet when there is room for part of one', () => {
    const result = truncateCommits(TEN_COMMITS, 3 * STUB_LINE + STUB_LINE - 1, fixedWidth)

    expect(result.commits).toHaveLength(3)
  })

  it('sizes each bullet independently rather than assuming a uniform width', () => {
    const { commits, measure } = commitsWithWidths([10, 20, 30, 40])

    // Cumulative cost, newline included: 11, 32, 63, 104.
    expect(truncateCommits(commits, 11, measure).commits).toHaveLength(1)
    expect(truncateCommits(commits, 32, measure).commits).toHaveLength(2)
    expect(truncateCommits(commits, 63, measure).commits).toHaveLength(3)
    expect(truncateCommits(commits, 104, measure).commits).toHaveLength(4)
    expect(truncateCommits(commits, 62, measure).commits).toHaveLength(2)
  })

  it('stops at the first bullet that does not fit instead of packing later ones in', () => {
    // Skipping the big one to fit the two small ones would hold more commits and
    // would also stop being the list the pull request's Commits tab shows (D6).
    const { commits, measure } = commitsWithWidths([100, 5, 5])
    const result = truncateCommits(commits, 50, measure)

    expect(result).toEqual({ commits: [], overflowCount: 3 })
  })

  it.each([0, 1, STUB_LINE - 1, -1, -10_000, Number.NaN])(
    'keeps nothing at all on a budget of %s',
    (budget) => {
      const result = truncateCommits(TEN_COMMITS, budget, fixedWidth)

      expect(result.commits).toEqual([])
      expect(result.overflowCount).toBe(TEN_COMMITS.length)
    },
  )

  it.each([0, 1, 1_000, Number.POSITIVE_INFINITY])(
    'returns an empty result for an empty list on a budget of %s',
    (budget) => {
      expect(truncateCommits([], budget, fixedWidth)).toEqual({ commits: [], overflowCount: 0 })
    },
  )
})

describe('the kept commits are a prefix, by identity', () => {
  it.each([0, 1, 2, 3, 4])('keeps the first %i objects themselves, never copies', (k) => {
    const result = truncateCommits(nonMonotonicCommits, k * STUB_LINE, fixedWidth)

    expect(result.commits).toHaveLength(k)
    result.commits.forEach((commit, index) => {
      expect(commit).toBe(nonMonotonicCommits[index])
    })
    expect(result.commits.length + result.overflowCount).toBe(nonMonotonicCommits.length)
  })

  it('does not reorder a list whose author dates decrease (D6)', () => {
    // Index 2 of this fixture is older than index 1. Anything that sorted by date
    // would move it, and the identity assertion below is what catches that.
    const result = truncateCommits(nonMonotonicCommits, 10_000, measureBullet)

    expect(result.commits.map((commit) => commit.subject)).toEqual([
      'Add the parser',
      'Handle the empty input',
      'Fix the off-by-one',
      'Document the parser',
    ])
    result.commits.forEach((commit, index) => {
      expect(commit).toBe(nonMonotonicCommits[index])
    })
  })

  it('does not mutate the array it was handed', () => {
    const commits = [...nonMonotonicCommits]
    const result = truncateCommits(commits, 2 * STUB_LINE, fixedWidth)

    expect(commits).toEqual(nonMonotonicCommits)
    expect(commits).toHaveLength(nonMonotonicCommits.length)
    expect(result.commits).not.toBe(commits)
  })
})

describe('module boundaries', () => {
  const source = readFileSync(
    fileURLToPath(new URL('../../src/render/truncate.ts', import.meta.url)),
    'utf8',
  )

  it('reads the source it is asserting over', () => {
    expect(source).toContain('export function truncateCommits')
  })

  it('never cuts a rendered string', () => {
    // The whole point of the module. A string-level cut can sever the end marker,
    // after which the block can never be found again.
    expect(source).not.toMatch(/\.substring\(|\.substr\(/)
  })

  it('slices the commit array and nothing else', () => {
    expect(source.match(/\.slice\(/g)).toHaveLength(1)
    expect(source).toContain('commits.slice(0, kept)')
  })

  it('does not import the assembler, which lands after it', () => {
    expect(source).not.toMatch(/from ['"].*block/)
  })

  it.each(['@actions', 'src/github', "from '../github", 'octokit'])(
    'never mentions %s, as the pure render layer',
    (forbidden) => {
      expect(source).not.toContain(forbidden)
    },
  )

  it('contains no ordering call at all (D6)', () => {
    expect(source).not.toMatch(/\.sort\(|\.reverse\(\)/)
  })

  it('takes its sizing from the injected measure, never from a renderer', () => {
    expect(source).not.toContain('renderCommitBullet')
    expect(source).not.toMatch(/from ['"]\.\/commits/)
  })
})
